-- =============================================
-- VELORA TRANSFER — 26 Bölge SEO Seed Data
-- 5 dil (tr/en/de/pl/ru) × 26 bölge
-- Meta title, meta description, mesafe, süre
-- =============================================

INSERT INTO regions (slug, name_tr, name_en, name_de, name_pl, name_ru,
  description_tr, description_en, description_de, description_pl, description_ru,
  meta_title_tr, meta_title_en, meta_title_de, meta_title_pl, meta_title_ru,
  meta_description_tr, meta_description_en, meta_description_de, meta_description_pl, meta_description_ru,
  distance_km, duration_minutes, is_popular, is_active, sort_order)
VALUES

-- 1. KUNDU
('kundu',
 'Kundu', 'Kundu', 'Kundu', 'Kundu', 'Кунду',
 'Antalya Havalimanı''ndan Kundu bölgesine VIP transfer hizmeti. Uçuş takibi, kapıdan kapıya hizmet ve sabit fiyat garantisi.',
 'VIP transfer service from Antalya Airport to Kundu area. Flight tracking, door-to-door service and fixed price guarantee.',
 'VIP-Transferservice vom Flughafen Antalya in die Region Kundu. Flugnachverfolgung, Tür-zu-Tür-Service und Festpreisgarantie.',
 'Usługa transferu VIP z lotniska Antalya do regionu Kundu. Śledzenie lotów, usługa door-to-door i gwarancja stałej ceny.',
 'VIP-трансфер из аэропорта Анталии в район Кунду. Отслеживание рейсов, от двери до двери и гарантия фиксированной цены.',
 'Antalya Havalimanı Kundu VIP Transfer | 7/24 Özel Araç',
 'VIP Transfer Antalya Airport to Kundu | Fixed Price',
 'Antalya Flughafen → Kundu VIP Transfer | Festpreis',
 'Transfer z lotniska Antalya → Kundu | VIP prywatny',
 'ВИП Трансфер из Анталии в Кунду | Фикс. цена',
 'Antalya Havalimanı''ndan Kundu''ya VIP/özel transfer. Uçuş takibi, karşılama, sabit fiyat ve online rezervasyon.',
 'Private VIP transfer from Antalya Airport to Kundu. Meet & greet, flight tracking, fixed pricing. Book online.',
 'Privater VIP-Transfer nach Kundu. Abholung mit Namensschild, Flugtracking, Festpreis. Online buchen.',
 'Prywatny VIP transfer do Kundu. Stała cena, monitoring lotu, spotkanie po przylocie. Rezerwuj online.',
 'Частный VIP-трансфер в Кунду: встреча, отслеживание рейса, фиксированная цена. Онлайн-бронирование.',
 12.0, 15, true, true, 1),

-- 2. LARA
('lara',
 'Lara', 'Lara', 'Lara', 'Lara', 'Лара',
 'Antalya Havalimanı''ndan Lara bölgesine VIP transfer. Lara otellerine kapıdan kapıya özel araç hizmeti.',
 'VIP transfer from Antalya Airport to Lara district. Door-to-door private vehicle service to Lara hotels.',
 'VIP-Transfer vom Flughafen Antalya nach Lara. Tür-zu-Tür Privatfahrzeug-Service zu Lara Hotels.',
 'Transfer VIP z lotniska Antalya do dzielnicy Lara. Usługa door-to-door do hoteli w Lara.',
 'VIP-трансфер из аэропорта Анталии в район Лара. Услуга от двери до двери до отелей Лары.',
 'Antalya Havalimanı Lara VIP Transfer | Sabit Fiyat',
 'Lara Beach Private Transfer | Antalya VIP Transport',
 'Antalya Flughafen → Lara Privattransfer | 24/7',
 'Transfer z lotniska Antalya → Lara | Prywatny',
 'Индивидуальный Трансфер Анталия – Лара',
 'Lara otellerine VIP transfer: karşılama, uçuş takibi, şeffaf fiyat. Hemen rezervasyon yapın.',
 'Door-to-door private transfer to Lara hotels. Reliable drivers, flight tracking, no hidden fees.',
 'Tür-zu-Tür Privattransfer nach Lara. Transparent, pünktlich, ohne versteckte Kosten.',
 'Transfer door-to-door do hoteli w Lara. Stała cena, bez ukrytych opłat, łatwa rezerwacja.',
 'Быстро и комфортно доставим вас в отель Лары. Фиксированная цена, бесплатные детские кресла и русскоговорящая поддержка.',
 14.0, 18, true, true, 2),

-- 3. BELEK
('belek',
 'Belek', 'Belek', 'Belek', 'Belek', 'Белек',
 'Antalya Havalimanı''ndan Belek''e VIP transfer. Golf tesisleri ve lüks otellere hızlı ve konforlu ulaşım.',
 'VIP transfer from Antalya Airport to Belek. Fast and comfortable transport to golf resorts and luxury hotels.',
 'VIP-Transfer vom Flughafen Antalya nach Belek. Schneller und komfortabler Transport zu Golfresorts und Luxushotels.',
 'Transfer VIP z lotniska Antalya do Belek. Szybki i komfortowy transport do pól golfowych i luksusowych hoteli.',
 'VIP-трансфер из аэропорта Анталии в Белек. Быстрый и комфортабельный транспорт до гольф-курортов и роскошных отелей.',
 'Antalya Havalimanı Belek VIP Transfer | Hızlı & Konforlu',
 'Premium Belek Airport Transfers | VIP Golf Transport',
 'Antalya Flughafen → Belek VIP Transfer | Komfort',
 'Transfer z lotniska Antalya → Belek | VIP',
 'ВИП Трансфер Аэропорт Анталия – Белек | Комфорт',
 'Belek''e VIP transfer: kapıdan kapıya, 7/24 destek, güvenli sürüş. Online rezervasyonla yerinizi ayırın.',
 'Book a VIP transfer to Belek resorts. Fixed price, meet & greet, family-friendly vehicles.',
 'VIP-Transfer zu Belek Resorts. Festpreis, Meet & Greet, komfortable Fahrzeuge.',
 'VIP transfer do Belek. Spotkanie na lotnisku, monitoring lotu, komfortowe auta.',
 'Премиум трансфер в отели Белека. Быстро, безопасно и с максимальным комфортом. Идеально для семей и гольфистов. Забронируйте сейчас.',
 33.0, 30, true, true, 3),

-- 4. SIDE
('side',
 'Side', 'Side', 'Side', 'Side', 'Сиде',
 'Antalya Havalimanı''ndan Side bölgesine VIP transfer. Antik kent ve sahil otellerine güvenli ulaşım.',
 'VIP transfer from Antalya Airport to Side region. Safe transport to ancient city and beachfront hotels.',
 'VIP-Transfer vom Flughafen Antalya nach Side. Sicherer Transport zur antiken Stadt und zu Strandhotels.',
 'Transfer VIP z lotniska Antalya do Side. Bezpieczny transport do starożytnego miasta i hoteli nadmorskich.',
 'VIP-трансфер из аэропорта Анталии в район Сиде. Безопасный транспорт до древнего города и пляжных отелей.',
 'Antalya Havalimanı Side VIP Transfer | Kapıdan Kapıya',
 'Private Transfer Antalya to Side | Fast & Safe Ride',
 'Antalya Flughafen → Side Privattransfer | Schnell',
 'Transfer z lotniska Antalya → Side | Prywatny',
 'Индивидуальный Трансфер Анталия – Сиде',
 'Side bölgesine özel transfer: uçuş gecikmesi takibi, Meet & Greet, sabit ücret. Kolay rezervasyon.',
 'Comfortable private transfer to Side. 24/7 support, flight monitoring, easy booking.',
 'Privattransfer nach Side. Flugüberwachung, 24/7 Support, einfache Buchung.',
 'Prywatny transfer do Side. Stała cena, 24/7 wsparcie, szybka rezerwacja.',
 'Комфортный VIP трансфер в Сиде. Просторные минивэны Mercedes, кондиционер и вода в салоне. Бронирование без предоплаты.',
 65.0, 55, true, true, 4),

-- 5. KEMER
('kemer',
 'Kemer', 'Kemer', 'Kemer', 'Kemer', 'Кемер',
 'Antalya Havalimanı''ndan Kemer''e VIP transfer. Doğa ile iç içe sahil otellerine konforlu ulaşım.',
 'VIP transfer from Antalya Airport to Kemer. Comfortable transport to seaside hotels surrounded by nature.',
 'VIP-Transfer vom Flughafen Antalya nach Kemer. Komfortabler Transport zu Strandhotels umgeben von Natur.',
 'Transfer VIP z lotniska Antalya do Kemer. Komfortowy transport do nadmorskich hoteli otoczonych naturą.',
 'VIP-трансфер из аэропорта Анталии в Кемер. Комфортабельный транспорт до морских отелей.',
 'Antalya Havalimanı Kemer VIP Transfer | 7/24 Rezervasyon',
 'Kemer VIP Airport Transfer | Antalya to Kemer Taxi',
 'Antalya Flughafen → Kemer VIP Transfer | Buchen',
 'Transfer z lotniska Antalya → Kemer | VIP',
 'ВИП Трансфер Анталия – Кемер | 24/7',
 'Kemer''e VIP transfer: konforlu araçlar, profesyonel sürücüler, sabit fiyat. Hızlı teklif alın.',
 'VIP transfer to Kemer hotels. Meet on arrival, fixed prices, professional service.',
 'VIP-Transfer nach Kemer. Meet & Greet, Festpreis, professioneller Service.',
 'VIP transfer do Kemer. Meet & greet, monitoring lotu, pewna rezerwacja.',
 'В Кемер: встреча, отслеживание рейса, фиксированная стоимость. Онлайн-заказ.',
 43.0, 45, true, true, 5),

-- 6. ALANYA
('alanya',
 'Alanya', 'Alanya', 'Alanya', 'Alanya', 'Аланья',
 'Antalya Havalimanı''ndan Alanya''ya VIP transfer. Uzun mesafede lüks ve konforlu yolculuk deneyimi.',
 'VIP transfer from Antalya Airport to Alanya. Luxury and comfortable long-distance travel experience.',
 'VIP-Transfer vom Flughafen Antalya nach Alanya. Luxuriöse und komfortable Langstreckenreise.',
 'Transfer VIP z lotniska Antalya do Alanyi. Luksusowa i komfortowa podróż na długim dystansie.',
 'VIP-трансфер из аэропорта Анталии в Аланью. Роскошное и комфортабельное путешествие на дальние расстояния.',
 'Antalya Havalimanı Alanya VIP Transfer | Özel Araç',
 'Antalya to Alanya Private VIP Transfer | Fixed Price',
 'Antalya Flughafen → Alanya Privattransfer | Festpreis',
 'Transfer z lotniska Antalya → Alanya | Prywatny',
 'Трансфер из Аэропорта Анталии в Аланью',
 'Alanya''ya VIP transfer: geniş bagaj, aile/grup araçları, uçuş takibi. Güvenle rezervasyon yapın.',
 'Long-distance private transfer to Alanya. Spacious vehicles, flight tracking, secure booking.',
 'Langer Strecke? Komfortabler Privattransfer nach Alanya. Viel Platz, sicher, fix buchen.',
 'Długi dystans do Alanyi? Wybierz prywatny transfer: stała cena, komfort i bezpieczeństwo.',
 '2 часа в пути пролетят незаметно с нашим VIP трансфером в Аланию. Просторный салон, Wi-Fi и абсолютный комфорт.',
 132.0, 120, true, true, 6),

-- 7. KAŞ
('kas',
 'Kaş', 'Kaş', 'Kaş', 'Kaş', 'Каш',
 'Antalya Havalimanı''ndan Kaş''a VIP transfer. Uzun mesafe premium yolculuk, sabit fiyat garantisi.',
 'VIP transfer from Antalya Airport to Kaş. Long-distance premium journey with fixed price guarantee.',
 'VIP-Transfer vom Flughafen Antalya nach Kaş. Langstrecken-Premiumfahrt mit Festpreisgarantie.',
 'Transfer VIP z lotniska Antalya do Kaş. Długodystansowa podróż premium z gwarancją stałej ceny.',
 'VIP-трансфер из аэропорта Анталии в Каш. Премиум-поездка на дальние расстояния с гарантией фиксированной цены.',
 'Antalya Havalimanı Kaş VIP Transfer | Lüks Ulaşım',
 'VIP Transfer from Antalya Airport to Kaş | Private Car',
 'Antalya Flughafen → Kas VIP Transfer | Privat',
 'Transfer z lotniska Antalya → Kas | VIP',
 'ВИП Трансфер из Анталии в Каш | Частный',
 'Kaş''a uzun mesafe VIP transfer: sabit fiyat, güvenli rota, konforlu yolculuk. Online rezervasyon.',
 'Premium private transfer to Kaş. Fixed price, meet & greet, stress-free journey.',
 'Premium Privattransfer nach Kas. Festpreis, Flugtracking, stressfreie Fahrt.',
 'VIP transfer do Kaş. Stała cena, monitoring lotu, wygodna podróż.',
 'VIP-трансфер в Каş: встреча, отслеживание рейса, прозрачная цена.',
 187.0, 195, true, true, 7),

-- 8. MANAVGAT
('manavgat',
 'Manavgat', 'Manavgat', 'Manavgat', 'Manavgat', 'Манавгат',
 'Antalya Havalimanı''ndan Manavgat''a VIP transfer. Şelaleler ve sahil otellerine konforlu ulaşım.',
 'VIP transfer from Antalya Airport to Manavgat. Comfortable transport to waterfalls and coastal hotels.',
 'VIP-Transfer vom Flughafen Antalya nach Manavgat. Komfortabler Transport zu Wasserfällen und Küstenhotels.',
 'Transfer VIP z lotniska Antalya do Manavgat. Komfortowy transport do wodospadów i nadmorskich hoteli.',
 'VIP-трансфер из аэропорта Анталии в Манавгат. Комфортабельный транспорт до водопадов и прибрежных отелей.',
 'Antalya Havalimanı Manavgat VIP Transfer | Sabit Ücret',
 'Private VIP Transfer to Manavgat | Antalya Airport',
 'Antalya Flughafen → Manavgat Privattransfer | 24/7',
 'Transfer z lotniska Antalya → Manavgat | Prywatny',
 'Индивидуальный Трансфер Анталия – Манавгат',
 'Manavgat''a özel transfer: karşılama, uçuş takibi, 7/24 destek. Hemen yer ayırtın.',
 'Door-to-door private transfer to Manavgat. Flight tracking and transparent pricing.',
 'Tür-zu-Tür Transfer nach Manavgat. Festpreis, Meet & Greet, online reservieren.',
 'Prywatny transfer do Manavgat. Spotkanie, stała cena, rezerwacja online.',
 'Надежный VIP трансфер в Манавгат. Оплата при встрече, без скрытых доплат. Профессиональные водители.',
 72.0, 60, false, true, 8),

-- 9. KONYAALTI
('konyaalti',
 'Konyaaltı', 'Konyaaltı', 'Konyaaltı', 'Konyaaltı', 'Коньяалты',
 'Antalya Havalimanı''ndan Konyaaltı''na VIP transfer. Şehir merkezine yakın plajlara hızlı ulaşım.',
 'VIP transfer from Antalya Airport to Konyaaltı. Quick transport to beaches near the city center.',
 'VIP-Transfer vom Flughafen Antalya nach Konyaaltı. Schneller Transport zu Stränden nahe dem Stadtzentrum.',
 'Transfer VIP z lotniska Antalya do Konyaaltı. Szybki transport na plaże blisko centrum miasta.',
 'VIP-трансфер из аэропорта Анталии в Коньяалты. Быстрый транспорт до пляжей рядом с центром города.',
 'Antalya Havalimanı Konyaaltı VIP Transfer | Hızlı Ulaşım',
 'Konyaalti Beach VIP Transfer | Private Antalya Taxi',
 'Antalya Flughafen → Konyaaltı Transfer | Schnell',
 'Transfer z lotniska Antalya → Konyaaltı | Szybko',
 'Трансфер Аэропорт Анталия – Коньяалты | Быстро',
 'Konyaaltı''na VIP transfer: kısa sürede varış, sabit fiyat ve güvenli sürüş. Online rezervasyon.',
 'Quick private transfer to Konyaaltı. Meet & greet, fixed price, easy reservation.',
 'Schneller Privattransfer nach Konyaaltı. Fixer Preis, Abholung, 24/7 Support.',
 'Szybki prywatny transfer do Konyaaltı. Stała cena i meet & greet.',
 'Прямой индивидуальный трансфер к пляжам Коньяалты. Роскошные автомобили и первоклассный сервис для вас.',
 18.0, 20, false, true, 9),

-- 10. BELDİBİ
('beldibi',
 'Beldibi', 'Beldibi', 'Beldibi', 'Beldibi', 'Бельдиби',
 'Antalya Havalimanı''ndan Beldibi''ye VIP transfer. Doğa ve deniz arasında konforlu tatil başlangıcı.',
 'VIP transfer from Antalya Airport to Beldibi. A comfortable holiday start between nature and sea.',
 'VIP-Transfer vom Flughafen Antalya nach Beldibi. Komfortabler Urlaubsstart zwischen Natur und Meer.',
 'Transfer VIP z lotniska Antalya do Beldibi. Komfortowy początek wakacji między naturą a morzem.',
 'VIP-трансфер из аэропорта Анталии в Бельдиби. Комфортное начало отдыха между природой и морем.',
 'Antalya Havalimanı Beldibi VIP Transfer | Özel Transfer',
 'Beldibi Private Airport Transfer | VIP Luxury Ride',
 'Antalya Flughafen → Beldibi VIP Transfer | Festpreis',
 'Transfer z lotniska Antalya → Beldibi | VIP',
 'ВИП Трансфер Аэропорт Анталия – Бельдиби | Фикс.',
 'Beldibi otellerine VIP transfer: kapıdan kapıya, uçuş takibi ve şeffaf fiyat. Rezervasyon yapın.',
 'Private VIP transfer to Beldibi. Comfortable vehicles, flight tracking, 24/7 support.',
 'VIP-Transfer nach Beldibi. Komfort, Flugtracking, transparente Preise.',
 'VIP transfer do Beldibi. Komfortowe auta, monitoring lotu, rezerwacja online.',
 'VIP-трансфер в Бельдиби: комфорт, отслеживание рейса, без доплат.',
 35.0, 35, false, true, 10),

-- 11. GÖYNÜK
('goynuk',
 'Göynük', 'Göynük', 'Göynük', 'Göynük', 'Гёйнюк',
 'Antalya Havalimanı''ndan Göynük''e VIP transfer. Aile dostu araçlar ve güvenli yolculuk.',
 'VIP transfer from Antalya Airport to Göynük. Family-friendly vehicles and safe journey.',
 'VIP-Transfer vom Flughafen Antalya nach Göynük. Familienfreundliche Fahrzeuge und sichere Fahrt.',
 'Transfer VIP z lotniska Antalya do Göynük. Pojazdy przyjazne rodzinom i bezpieczna podróż.',
 'VIP-трансфер из аэропорта Анталии в Гёйнюк. Семейные автомобили и безопасная поездка.',
 'Antalya Havalimanı Göynük VIP Transfer | 7/24 Hizmet',
 'VIP Transfer Antalya to Göynük | Family Friendly',
 'Antalya Flughafen → Göynük Privattransfer | Buchen',
 'Transfer z lotniska Antalya → Göynük | Prywatny',
 'Индивидуальный Трансфер в Гёйнюк',
 'Göynük''e özel transfer: Meet & Greet, sabit ücret, konforlu araçlar. Hızlı rezervasyon.',
 'Reliable private transfer to Göynük hotels. Meet & greet and fixed pricing.',
 'Privattransfer nach Göynük Hotels. Meet & Greet, zuverlässiger Service.',
 'Prywatny transfer do Göynük. Stała cena, bez stresu, łatwa rezerwacja.',
 'Идеальный выбор для семей. Просторный VIP трансфер в Гёйнюк. Бронируйте онлайн за пару минут без предоплаты.',
 38.0, 38, false, true, 11),

-- 12. TEKİROVA
('tekirova',
 'Tekirova', 'Tekirova', 'Tekirova', 'Tekirova', 'Текирова',
 'Antalya Havalimanı''ndan Tekirova''ya VIP transfer. Olympos dağları eteklerinde huzurlu bir başlangıç.',
 'VIP transfer from Antalya Airport to Tekirova. A peaceful start at the foothills of Olympos mountains.',
 'VIP-Transfer vom Flughafen Antalya nach Tekirova. Ein friedlicher Start am Fuße des Olympos-Gebirges.',
 'Transfer VIP z lotniska Antalya do Tekirova. Spokojny początek u podnóża gór Olympos.',
 'VIP-трансфер из аэропорта Анталии в Текирова. Спокойное начало у подножия гор Олимпос.',
 'Antalya Havalimanı Tekirova VIP Transfer | Konforlu',
 'Tekirova VIP Transfer | Premium Antalya Airport Taxi',
 'Antalya Flughafen → Tekirova VIP Transfer | Komfort',
 'Transfer z lotniska Antalya → Tekirova | VIP',
 'ВИП Трансфер из Анталии в Текирова | Комфорт',
 'Tekirova''ya VIP transfer: uzun rota konforu, ticari sürüş değil özel hizmet. Online rezervasyon.',
 'VIP transfer to Tekirova. Safe ride, professional drivers, online booking.',
 'Reisen Sie First-Class nach Tekirova. Unser VIP-Transfer bietet absolute Privatsphäre und exzellenten Service.',
 'Podróżuj pierwszą klasą do Tekirova. Nasz VIP transfer oferuje absolutną prywatność i doskonałą obsługę.',
 'Роскошный путь до Текирова на наших премиум минивэнах. Высокий уровень сервиса и пунктуальность гарантированы.',
 55.0, 50, false, true, 12),

-- 13. ÇAMYUVA
('camyuva',
 'Çamyuva', 'Çamyuva', 'Çamyuva', 'Çamyuva', 'Чамьюва',
 'Antalya Havalimanı''ndan Çamyuva''ya VIP transfer. Doğal güzellikler arasında konforlu yolculuk.',
 'VIP transfer from Antalya Airport to Çamyuva. Comfortable journey among natural beauties.',
 'VIP-Transfer vom Flughafen Antalya nach Çamyuva. Komfortable Fahrt inmitten natürlicher Schönheit.',
 'Transfer VIP z lotniska Antalya do Çamyuva. Komfortowa podróż wśród naturalnych piękności.',
 'VIP-трансфер из аэропорта Анталии в Чамьюва. Комфортабельная поездка среди природных красот.',
 'Antalya Havalimanı Çamyuva VIP Transfer | Sabit Fiyat',
 'Camyuva Private Transfer | Antalya Airport VIP Ride',
 'Antalya Flughafen → Çamyuva Privattransfer | Festpreis',
 'Transfer z lotniska Antalya → Çamyuva | Prywatny',
 'Трансфер Аэропорт Анталия – Чамьюва',
 'Çamyuva''ya VIP transfer: uçuş gecikmesi takibi, karşılama, ekstra ücret yok. Rezervasyon yapın.',
 'Door-to-door private transfer to Çamyuva. Flight tracking, no hidden fees.',
 'Tür-zu-Tür Transfer nach Çamyuva. Flugtracking, keine versteckten Gebühren.',
 'Transfer door-to-door do Çamyuva. Monitoring lotu, stała cena, book online.',
 'Door-to-door в Чамьюва: фикс. цена, без скрытых платежей, бронь онлайн.',
 50.0, 48, false, true, 13),

-- 14. OLYMPOS
('olympos',
 'Olympos', 'Olympos', 'Olympos', 'Olympos', 'Олимпос',
 'Antalya Havalimanı''ndan Olympos''a VIP transfer. Doğanın kalbine güvenli ve konforlu ulaşım.',
 'VIP transfer from Antalya Airport to Olympos. Safe and comfortable transport to the heart of nature.',
 'VIP-Transfer vom Flughafen Antalya nach Olympos. Sicherer und komfortabler Transport ins Herz der Natur.',
 'Transfer VIP z lotniska Antalya do Olympos. Bezpieczny i komfortowy transport w serce natury.',
 'VIP-трансфер из аэропорта Анталии в Олимпос. Безопасный и комфортабельный транспорт в сердце природы.',
 'Antalya Havalimanı Olympos VIP Transfer | Özel Araç',
 'VIP Transfer to Olympos | Private Ride from Antalya',
 'Antalya Flughafen → Olympos Privattransfer | 24/7',
 'Transfer z lotniska Antalya → Olympos | Prywatny',
 'Индивидуальный Трансфер в Олимпос',
 'Olympos''a VIP transfer: güvenli uzun mesafe sürüş, sabit fiyat, hızlı rezervasyon.',
 'Private transfer to Olympos. Fixed price, meet & greet, comfortable travel.',
 'Luxuriöser VIP-Transfer in die Natur von Olympos. Entspannen Sie sich in unseren klimatisierten Fahrzeugen.',
 'Luksusowy VIP transfer do natury Olympos. Zrelaksuj się w naszych klimatyzowanych pojazdach.',
 'Комфортная поездка в природу Олимпоса на VIP авто. Ваш личный водитель встретит вас в аэропорту.',
 80.0, 75, false, true, 14),

-- 15. ADRASAN
('adrasan',
 'Adrasan', 'Adrasan', 'Adrasan', 'Adrasan', 'Адрасан',
 'Antalya Havalimanı''ndan Adrasan''a VIP transfer. Saklı cennet Adrasan''a özel ulaşım.',
 'VIP transfer from Antalya Airport to Adrasan. Private transport to the hidden paradise of Adrasan.',
 'VIP-Transfer vom Flughafen Antalya nach Adrasan. Privater Transport zum verborgenen Paradies Adrasan.',
 'Transfer VIP z lotniska Antalya do Adrasan. Prywatny transport do ukrytego raju Adrasan.',
 'VIP-трансфер из аэропорта Анталии в Адрасан. Частный транспорт в скрытый рай Адрасан.',
 'Antalya Havalimanı Adrasan VIP Transfer | 7/24 Rezervasyon',
 'Private Transfer Antalya to Adrasan | VIP Service',
 'Antalya Flughafen → Adrasan VIP Transfer | Buchen',
 'Transfer z lotniska Antalya → Adrasan | VIP',
 'ВИП Трансфер Анталия – Адрасан | 24/7',
 'Adrasan''a VIP transfer: konforlu araç, kapıdan kapıya hizmet, uçuş takibi. Rezervasyon yapın.',
 'VIP private transfer to Adrasan. Flight monitoring, fixed rates, easy reservation.',
 'Exklusiver Transport nach Adrasan. Buchen Sie jetzt Ihren Privattransfer für eine sichere und komfortable Anreise.',
 'Ekskluzywny transport do Adrasan. Zarezerwuj swój prywatny transfer teraz dla bezpiecznej podróży.',
 'Премиум трансфер на дальнее расстояние в Адрасан. Вода, Wi-Fi и полная безопасность на дороге.',
 90.0, 85, false, true, 15),

-- 16. DEMRE
('demre',
 'Demre', 'Demre', 'Demre', 'Demre', 'Демре',
 'Antalya Havalimanı''ndan Demre''ye VIP transfer. Noel Baba''nın memleketi Demre''ye lüks ulaşım.',
 'VIP transfer from Antalya Airport to Demre. Luxury transport to the homeland of St. Nicholas.',
 'VIP-Transfer vom Flughafen Antalya nach Demre. Luxustransport in die Heimat des Heiligen Nikolaus.',
 'Transfer VIP z lotniska Antalya do Demre. Luksusowy transport do ojczyzny Świętego Mikołaja.',
 'VIP-трансфер из аэропорта Анталии в Демре. Роскошный транспорт на родину Святого Николая.',
 'Antalya Havalimanı Demre VIP Transfer | Lüks Transfer',
 'Demre VIP Airport Transfer | Long Distance Luxury',
 'Antalya Flughafen → Demre Privattransfer | Festpreis',
 'Transfer z lotniska Antalya → Demre | Prywatny',
 'Трансфер из Анталии в Демре | ВИП Сервис',
 'Demre''ye VIP transfer: güvenli rota, sabit ücret, hızlı teklif. Online rezervasyon kolaylığı.',
 'Long-distance private transfer to Demre. Safe route, transparent pricing.',
 'Langstrecke nach Demre mit Privattransfer. Sicher, komfortabel, transparent.',
 'Prywatny transfer do Demre. Bezpieczna trasa, stała cena.',
 'Дальний трансфер в Демре: безопасно, комфортно, прозрачная цена.',
 145.0, 140, false, true, 16),

-- 17. FİNİKE
('finike',
 'Finike', 'Finike', 'Finike', 'Finike', 'Финике',
 'Antalya Havalimanı''ndan Finike''ye VIP transfer. Batı Antalya''nın güzelliklerine konforlu ulaşım.',
 'VIP transfer from Antalya Airport to Finike. Comfortable transport to the beauties of Western Antalya.',
 'VIP-Transfer vom Flughafen Antalya nach Finike. Komfortabler Transport zu den Schönheiten Westantalyas.',
 'Transfer VIP z lotniska Antalya do Finike. Komfortowy transport do piękności zachodniej Antalyi.',
 'VIP-трансфер из аэропорта Анталии в Финике. Комфортабельный транспорт до красот Западной Анталии.',
 'Antalya Havalimanı Finike VIP Transfer | Özel Ulaşım',
 'Finike Private VIP Transfer | Reliable AYT Taxi',
 'Antalya Flughafen → Finike VIP Transfer | Privat',
 'Transfer z lotniska Antalya → Finike | VIP',
 'ВИП Трансфер Аэропорт Анталия – Финике | Частный',
 'Finike''ye VIP transfer: uzun mesafe konforu, uçuş takibi, karşılama. Hemen rezervasyon yapın.',
 'Book a VIP transfer to Finike. Meet & greet, flight tracking, fixed price.',
 'Direkter und bequemer Privattransfer nach Finike. Top-Bewertungen, transparente Preise und hervorragender Service.',
 'VIP transfer do Finike. Spotkanie na lotnisku i monitoring lotu.',
 'VIP-трансфер в Финике: встреча, отслеживание рейса, фикс. стоимость.',
 160.0, 155, false, true, 17),

-- 18. KUMLUCA
('kumluca',
 'Kumluca', 'Kumluca', 'Kumluca', 'Kumluca', 'Кумлуджа',
 'Antalya Havalimanı''ndan Kumluca''ya VIP transfer. Sakin tatil beldelerine özel ulaşım.',
 'VIP transfer from Antalya Airport to Kumluca. Private transport to quiet holiday towns.',
 'VIP-Transfer vom Flughafen Antalya nach Kumluca. Privater Transport zu ruhigen Ferienorten.',
 'Transfer VIP z lotniska Antalya do Kumluca. Prywatny transport do spokojnych miejscowości wypoczynkowych.',
 'VIP-трансфер из аэропорта Анталии в Кумлуджа. Частный транспорт до тихих курортных городков.',
 'Antalya Havalimanı Kumluca VIP Transfer | Sabit Ücret',
 'VIP Transfer Antalya to Kumluca | Private Minivans',
 'Antalya Flughafen → Kumluca Privattransfer | 24/7',
 'Transfer z lotniska Antalya → Kumluca | Prywatny',
 'ВИП Трансфер в Кумлуджа из Аэропорта',
 'Kumluca''ya özel transfer: şeffaf fiyat, güvenli sürüş, 7/24 destek. Online rezervasyon.',
 'Door-to-door private transfer to Kumluca. Fixed price and fast booking.',
 'Tür-zu-Tür Transfer nach Kumluca. Fixpreis, schnell buchen.',
 'Transfer do Kumluca: stała cena, prosta rezerwacja, 24/7 wsparcie.',
 'Закажите премиум такси в Кумлуджа. Мы отслеживаем рейсы, поэтому дождемся вас даже при задержке.',
 120.0, 115, false, true, 18),

-- 19. GAZİPAŞA
('gazipasa',
 'Gazipaşa', 'Gazipaşa', 'Gazipaşa', 'Gazipaşa', 'Газипаша',
 'Antalya Havalimanı''ndan Gazipaşa''ya VIP transfer. Doğu Antalya''ya konforlu uzun mesafe ulaşım.',
 'VIP transfer from Antalya Airport to Gazipaşa. Comfortable long-distance transport to Eastern Antalya.',
 'VIP-Transfer vom Flughafen Antalya nach Gazipaşa. Komfortabler Langstreckentransport nach Ostantalya.',
 'Transfer VIP z lotniska Antalya do Gazipaşa. Komfortowy transport dalekobieżny do wschodniej Antalyi.',
 'VIP-трансфер из аэропорта Анталии в Газипаша. Комфортабельный транспорт на дальние расстояния в Восточную Анталию.',
 'Antalya Havalimanı Gazipaşa VIP Transfer | Özel Araç',
 'Gazipasa VIP Transfer from Antalya Airport | Fixed Price',
 'Antalya Flughafen → Gazipaşa Privattransfer | Festpreis',
 'Transfer z lotniska Antalya → Gazipaşa | Prywatny',
 'Трансфер Аэропорт Анталия – Газипаша | Частный',
 'Gazipaşa''ya VIP transfer: uzun rota, sabit fiyat ve karşılama. Rezervasyonla beklemeden çıkın.',
 'Need a reliable transfer to Gazipasa? Our luxury private minivans offer the most comfortable long-distance ride available.',
 'Komfortabler Privattransfer vom Flughafen Antalya nach Gazipasa. Absolute Pünktlichkeit und Festpreis garantiert.',
 'Komfortowy prywatny przejazd z lotniska Antalya do Gazipasa. Absolutna punktualność gwarantowana.',
 'Трансфер в Газипаша: встреча, отслеживание рейса, фикс. цена.',
 175.0, 165, false, true, 19),

-- 20. OKURCALAR
('okurcalar',
 'Okurcalar', 'Okurcalar', 'Okurcalar', 'Okurcalar', 'Окурджалар',
 'Antalya Havalimanı''ndan Okurcalar''a VIP transfer. All-inclusive tatil beldelerine özel ulaşım.',
 'VIP transfer from Antalya Airport to Okurcalar. Private transport to all-inclusive holiday resorts.',
 'VIP-Transfer vom Flughafen Antalya nach Okurcalar. Privater Transport zu All-Inclusive-Ferienresorts.',
 'Transfer VIP z lotniska Antalya do Okurcalar. Prywatny transport do kurortów all-inclusive.',
 'VIP-трансфер из аэропорта Анталии в Окурджалар. Частный транспорт до курортов all-inclusive.',
 'Antalya Havalimanı Okurcalar VIP Transfer | Konforlu',
 'Okurcalar Private Transfer | VIP Antalya Airport Ride',
 'Antalya Flughafen → Okurcalar Privattransfer | Buchen',
 'Transfer z lotniska Antalya → Okurcalar | Prywatny',
 'Индивидуальный Трансфер в Окурджалар',
 'Okurcalar otellerine VIP transfer: uçuş takibi, kapıdan kapıya, sabit ücret.',
 'Private transfer to Okurcalar hotels. Fixed price, flight monitoring, 24/7 support.',
 'Privattransfer zu Okurcalar Hotels. Festpreis, 24/7 Support.',
 'Prywatny transfer do Okurcalar hoteli. Stała cena, 24/7 wsparcie.',
 'До отелей Окурджалара: фикс. стоимость, встреча, 24/7 поддержка.',
 100.0, 90, false, true, 20),

-- 21. TÜRKLER
('turkler',
 'Türkler', 'Türkler', 'Türkler', 'Türkler', 'Тюрклер',
 'Antalya Havalimanı''ndan Türkler bölgesine VIP transfer. Sahil otellerine konforlu ulaşım.',
 'VIP transfer from Antalya Airport to Türkler. Comfortable transport to coastal hotels.',
 'VIP-Transfer vom Flughafen Antalya nach Türkler. Komfortabler Transport zu Küstenhotels.',
 'Transfer VIP z lotniska Antalya do Türkler. Komfortowy transport do nadmorskich hoteli.',
 'VIP-трансфер из аэропорта Анталии в Тюрклер. Комфортабельный транспорт до морских отелей.',
 'Antalya Havalimanı Türkler VIP Transfer | 7/24 Hizmet',
 'Turkler VIP Transfer | Premium Antalya Airport Taxi',
 'Antalya Flughafen → Türkler VIP Transfer | Festpreis',
 'Transfer z lotniska Antalya → Türkler | VIP',
 'ВИП Трансфер из Анталии в Тюрклер | Фикс.',
 'Türkler bölgesine VIP transfer: geniş araç seçimi, şeffaf fiyat, hızlı rezervasyon.',
 'VIP private transfer to Türkler. Door-to-door, no hidden fees, easy booking.',
 'VIP-Transfer nach Türkler. Tür-zu-Tür, ohne versteckte Kosten.',
 'VIP transfer do Türkler. Door-to-door, bez dodatkowych opłat.',
 'Начните отпуск правильно с нашим премиум трансфером в Тюрклер. Встреча с табличкой у выхода.',
 110.0, 95, false, true, 21),

-- 22. AVSALLAR
('avsallar',
 'Avsallar', 'Avsallar', 'Avsallar', 'Avsallar', 'Авсаллар',
 'Antalya Havalimanı''ndan Avsallar''a VIP transfer. Huzurlu sahil kasabasına özel ulaşım.',
 'VIP transfer from Antalya Airport to Avsallar. Private transport to the peaceful coastal town.',
 'VIP-Transfer vom Flughafen Antalya nach Avsallar. Privater Transport zur friedlichen Küstenstadt.',
 'Transfer VIP z lotniska Antalya do Avsallar. Prywatny transport do spokojnego nadmorskiego miasteczka.',
 'VIP-трансфер из аэропорта Анталии в Авсаллар. Частный транспорт до спокойного прибрежного городка.',
 'Antalya Havalimanı Avsallar VIP Transfer | Sabit Fiyat',
 'Private Transfer AYT to Avsallar | VIP Service',
 'Antalya Flughafen → Avsallar Privattransfer | 24/7',
 'Transfer z lotniska Antalya → Avsallar | Prywatny',
 'Трансфер Аэропорт Анталия – Авсаллар | Частный',
 'Avsallar''a VIP transfer: Meet & Greet, uçuş takibi, ekstra ücret yok.',
 'Private transfer to Avsallar. Meet on arrival, fixed price, reserve online.',
 'Meet & Greet und Festpreis nach Avsallar. Online buchen.',
 'Transfer do Avsallar. Stała cena, meet & greet, rezerwacja online.',
 'В Авсаллар: meet & greet, фикс. цена, бронирование онлайн.',
 115.0, 100, false, true, 22),

-- 23. KONAKLI
('konakli',
 'Konaklı', 'Konaklı', 'Konaklı', 'Konaklı', 'Конаклы',
 'Antalya Havalimanı''ndan Konaklı''ya VIP transfer. Alanya yakınlarındaki popüler tatil beldesi.',
 'VIP transfer from Antalya Airport to Konaklı. Popular holiday resort near Alanya.',
 'VIP-Transfer vom Flughafen Antalya nach Konaklı. Beliebter Ferienort nahe Alanya.',
 'Transfer VIP z lotniska Antalya do Konaklı. Popularna miejscowość wypoczynkowa w pobliżu Alanyi.',
 'VIP-трансфер из аэропорта Анталии в Конаклы. Популярный курорт рядом с Аланьей.',
 'Antalya Havalimanı Konaklı VIP Transfer | Özel Transfer',
 'Konakli VIP Airport Transfer | Luxury Private Ride',
 'Antalya Flughafen → Konaklı Privattransfer | Festpreis',
 'Transfer z lotniska Antalya → Konaklı | Prywatny',
 'ВИП Трансфер в Конаклы | Премиум Сервис',
 'Konaklı''ya özel transfer: konforlu araç, kapıdan kapıya, online rezervasyon.',
 'Door-to-door private transfer to Konaklı. Flight tracking and transparent pricing.',
 'Tür-zu-Tür Transfer nach Konaklı. Flugtracking, transparente Preise.',
 'Prywatny transfer do Konaklı. Monitoring lotu, stała cena.',
 'Частный трансфер в Конаклы: отслеживание рейса, прозрачная цена.',
 120.0, 105, false, true, 23),

-- 24. MAHMUTLAR
('mahmutlar',
 'Mahmutlar', 'Mahmutlar', 'Mahmutlar', 'Mahmutlar', 'Махмутлар',
 'Antalya Havalimanı''ndan Mahmutlar''a VIP transfer. Alanya''nın doğusundaki popüler sahil kasabası.',
 'VIP transfer from Antalya Airport to Mahmutlar. Popular coastal town east of Alanya.',
 'VIP-Transfer vom Flughafen Antalya nach Mahmutlar. Beliebte Küstenstadt östlich von Alanya.',
 'Transfer VIP z lotniska Antalya do Mahmutlar. Popularne nadmorskie miasteczko na wschód od Alanyi.',
 'VIP-трансфер из аэропорта Анталии в Махмутлар. Популярный прибрежный городок к востоку от Аланьи.',
 'Antalya Havalimanı Mahmutlar VIP Transfer | Lüks',
 'Mahmutlar Private Transfer | VIP Ride from Antalya',
 'Antalya Flughafen → Mahmutlar Privattransfer | Buchen',
 'Transfer z lotniska Antalya → Mahmutlar | Prywatny',
 'Индивидуальный Трансфер Анталия – Махмутлар',
 'Mahmutlar''a VIP transfer: uzun mesafe konforu, aile/grup araçları, sabit fiyat.',
 'Long-distance private transfer to Mahmutlar. Spacious vehicles and fixed pricing.',
 'Langstrecken-Transfer nach Mahmutlar. Viel Platz, Fixpreis.',
 'Dłuższa trasa? Prywatny transfer do Mahmutlar: komfort i stała cena.',
 'Комфортабельный VIP трансфер на дальние расстояния в Махмутлар. Ваш идеальный выбор для поездки.',
 140.0, 130, false, true, 24),

-- 25. KESTEL
('kestel',
 'Kestel', 'Kestel', 'Kestel', 'Kestel', 'Кестель',
 'Antalya Havalimanı''ndan Kestel''e VIP transfer. Alanya yakınlarında sakin ve huzurlu tatil bölgesi.',
 'VIP transfer from Antalya Airport to Kestel. Quiet and peaceful holiday area near Alanya.',
 'VIP-Transfer vom Flughafen Antalya nach Kestel. Ruhige Urlaubsregion nahe Alanya.',
 'Transfer VIP z lotniska Antalya do Kestel. Cichy i spokojny region wakacyjny w pobliżu Alanyi.',
 'VIP-трансфер из аэропорта Анталии в Кестель. Тихий курортный район рядом с Аланьей.',
 'Antalya Havalimanı Kestel VIP Transfer | Sabit Ücret',
 'Kestel VIP Transfer | Private Antalya Airport Taxi',
 'Antalya Flughafen → Kestel Privattransfer | Festpreis',
 'Transfer z lotniska Antalya → Kestel | Prywatny',
 'Трансфер Анталия – Кестель | ВИП Такси',
 'Kestel''e VIP transfer: uçuş takibi, karşılama, güvenli sürüş. Hızlı rezervasyon.',
 'Private transfer to Kestel. Meet & greet, flight monitoring, secure booking.',
 'Privattransfer nach Kestel. Abholung, Flugüberwachung, sicher buchen.',
 'Prywatny transfer do Kestel. Meet & greet, monitoring lotu, book online.',
 'В Кестель: встреча, отслеживание рейса, безопасная бронь онлайн.',
 128.0, 115, false, true, 25),

-- 26. ANTALYA ŞEHİR MERKEZİ
('antalya-city-center',
 'Antalya Şehir Merkezi', 'Antalya City Center', 'Antalya Stadtzentrum', 'Centrum Antalyi', 'Центр Анталии',
 'Antalya Havalimanı''ndan şehir merkezine VIP transfer. Kaleiçi ve merkeze hızlı ve konforlu ulaşım.',
 'VIP transfer from Antalya Airport to city center. Fast and comfortable transport to Kaleiçi and downtown.',
 'VIP-Transfer vom Flughafen Antalya ins Stadtzentrum. Schneller Transport nach Kaleiçi und Innenstadt.',
 'Transfer VIP z lotniska Antalya do centrum miasta. Szybki transport do Kaleiçi i śródmieścia.',
 'VIP-трансфер из аэропорта Анталии в центр города. Быстрый транспорт до Калеичи и центра.',
 'Antalya Havalimanı Şehir Merkezi VIP Transfer | Hızlı',
 'Antalya City Center VIP Transfer | Kaleici Transport',
 'Antalya Flughafen → Stadtzentrum Transfer | Schnell',
 'VIP Transfer do Centrum Antalyi (Kaleiçi)',
 'ВИП Трансфер в Центр Анталии (Калеичи)',
 'Şehir merkezine VIP transfer: hızlı varış, sabit fiyat, 7/24 destek. Online rezervasyon.',
 'Quick private transfer to Antalya city center. Fixed price, meet & greet, 24/7 support.',
 'Direkter Privattransfer in die Innenstadt und Altstadt (Kaleici) von Antalya. Pünktlich, sicher und komfortabel.',
 'Bezpośredni prywatny transfer do centrum miasta i na Stare Miasto (Kaleici). Punktualnie i bezpiecznie.',
 'Роскошный трансфер в центр города и Старый город. Быстро, стильно и невероятно удобно.',
 15.0, 18, true, true, 26)
ON CONFLICT (slug) DO UPDATE SET
  name_tr = EXCLUDED.name_tr, name_en = EXCLUDED.name_en, name_de = EXCLUDED.name_de, name_pl = EXCLUDED.name_pl, name_ru = EXCLUDED.name_ru,
  description_tr = EXCLUDED.description_tr, description_en = EXCLUDED.description_en, description_de = EXCLUDED.description_de, description_pl = EXCLUDED.description_pl, description_ru = EXCLUDED.description_ru,
  meta_title_tr = EXCLUDED.meta_title_tr, meta_title_en = EXCLUDED.meta_title_en, meta_title_de = EXCLUDED.meta_title_de, meta_title_pl = EXCLUDED.meta_title_pl, meta_title_ru = EXCLUDED.meta_title_ru,
  meta_description_tr = EXCLUDED.meta_description_tr, meta_description_en = EXCLUDED.meta_description_en, meta_description_de = EXCLUDED.meta_description_de, meta_description_pl = EXCLUDED.meta_description_pl, meta_description_ru = EXCLUDED.meta_description_ru,
  distance_km = EXCLUDED.distance_km, duration_minutes = EXCLUDED.duration_minutes, is_popular = EXCLUDED.is_popular, is_active = EXCLUDED.is_active, sort_order = EXCLUDED.sort_order;
